### PR TITLE
Improved DockerContainer

### PR DESCRIPTION
**Pull request by ovo-Tim**
Hi, I found there are several problems of DockerContainer, so I made some improvement:
1.**Enhanced Error Messaging:**  Now, when an issue occurs, it will display a more informative error message, provide clearer feedback to users.
Before:
image
After:
image
2. **Improved Method for Getting Container IDs:** In order to streamline the process of getting container IDs, I have modified the method to parse the output of the `docker run` command directly. This change ensures that we can reliably capture the ID.
3. Prevent the user interface from freezing while commands are being executed.

I also removed `stop_container` function. Because I found that even if there are not only one containers are running, there won't be any problem. And previous method might accidently end the user's other container(User might open multiple pages that are using CfdOF, which could result in the termination of containers being utilized by other pages). 

<del>I have tried to make it clean up its own container, but it's not working:
code 
</del>

Update:
Cleanup is working now. https://github.com/jaheyns/CfdOF/pull/191#issuecomment-2480394723 :partying_face:

Just like in #188, I also have several tests failed(those items also can't pass on the main branch).

### CODE REVIEW

**Comment by oliveroxtoby** [comment]
@mmcker perhaps you could have a look at this one?

**Comment by mmcker** [comment]
The changes look good  - thanks for these.  

I also have a few changes I'll add after these (change the mount in the container to /tmp/cfdof rather than /tmp). 

One question - you note this: "might accidently end the user's other container(User might **open multiple pages** that are using CfdOF, which could result in the termination of containers being utilized by other pages)".

Yes - agreed.  When the code was written I didn't consider multiple pages being active - there is only one instance of the docker class at any one time, but this could be updated so it is one instance per page.  

I suggest for now that the program should cleanup after Freecad finishes  - so I think we need to get your cleanup code to work. I haven't tried your code, but not sure why it wouldn't work.

Testing - I test the following after making changes:
Platforms: 

- Windows with podman, 
- Debian: podman / docker, 
- Fedora: podman / docker 

Tests: 
- Start with check dependencies
- Start from mesh panel
- Start from run simulation panel

I don't expect your changes to have altered anything but have you done any tests at least with podman on windows?

Thanks Mark

**Comment by ovo-Tim** [comment]
Thanks, you are a really kind person. :smiley:

I have tried several possible solution, including `FreeCADGui.getMainWindow().mainWindowClosed` `QtGui.getMainWindow().mainWindowClosed` `QtGui.QApplication.instance().aboutToQuit` and `atexit`. But none of them works. :thinking:

**Comment by mmcker** [comment]
Have you looked at InitGui.py?

This code was there - not sure if you have removed it

```
    def __del__(sef):
        from CfdOF import CfdTools
        if CfdTools.DockerContainer.container_id != None:
            CfdTools.docker_container.stop_container()
```

**Comment by ovo-Tim** [comment]
This indeed will be excused when exit. But I don't think `CfdTools.DockerContainer.container_id` can get the container ID.

For example:
``` python
class test_class:
    id = None
    def __init__(self, id):
        self.id = id

cls = test_class(1)

print(cls.id)
print(test_class.id)
```
Output:
```
1
None
```

So I modified the code to:
``` python
def __del__(sef):
    from CfdOF import CfdTools
    if CfdTools.docker_container is not None:
        CfdTools.docker_container.clean_container()
        print("Container stopped.")
```

Thanks to your advice, this works now! :hugs:

**Comment by mmcker** [comment]
Thanks - looks good - previously we have not set the id in this fashion (def __init__(self, id):) - there was only one instance of the container so it had a shared (perhaps not an ideal way to code it though).

But thanks for your inputs - I will test across the platforms.  

I think @oliveroxtoby has a preference that the commit comments are also tidied up

**Comment by ovo-Tim** [comment]
Thanks for testing. :hugs: I just borrowed my friend's windows laptop, but I found its windows version is too old to install podman. 

> I think @oliveroxtoby has a preference that the commit comments are also tidied up

I don't think commit comments can be modified,. Do you mean I should update the pull request description? :thinking:

**Comment by ovo-Tim** [comment]
@mmcker Is this ready to be merged? :eyes:

**Comment by oliveroxtoby** [comment]
> I don't think commit comments can be modified,. Do you mean I should update the pull request description? 🤔

You can do a rebase to modify your commits (git rebase -i is particularly useful) and then force-push the results (git push -f). It would be nice to have more descriptive comments and/or squash them together into logical chunks.

**Comment by mmcker** [comment]
Hi @ovo-Tim 

It looks mostly good to me - tested on Windows and Fedora.

The one niggling issue is that using subprocess for starting and stopping the container on windows seems to open a new command window.  Qprocess doesn't do this.  Can the same functionality be implemented using qprocess and not the subprocess?  Alternatively - is there a setting in the subprocess which would stop the command window from opening on windows?

If this isn't possible, don't worry - it is fine and the commit is fine - but noting Oliver's advice on how to put more descriptive comments in the commit.

**Comment by ovo-Tim** [comment]
> The one niggling issue is that using subprocess for starting and stopping the container on windows seems to open a new command window. Qprocess doesn't do this. Can the same functionality be implemented using qprocess and not the subprocess? Alternatively - is there a setting in the subprocess which would stop the command window from opening on windows?

@mmcker I'm testing those codes on my virtual machine and the console window seemed not be opened.
<details>
<summary>codes</summary>

```python
import sys
import subprocess
from PySide6.QtWidgets import QApplication, QMainWindow, QPushButton, QTextEdit, QVBoxLayout, QWidget
from PySide6.QtCore import QThread, Signal

class CommandThread(QThread):
    output_signal = Signal(str)

    def __init__(self, command):
        super().__init__()
        self.command = command

    def run(self):
        process = subprocess.Popen(self.command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        for line in process.stdout:
            self.output_signal.emit(line)
        process.wait()

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("Subprocess Example")
        self.setGeometry(100, 100, 600, 400)

        self.text_edit = QTextEdit(self)
        self.text_edit.setReadOnly(True)

        self.button = QPushButton("Run Command", self)
        self.button.clicked.connect(self.run_command)

        layout = QVBoxLayout()
        layout.addWidget(self.text_edit)
        layout.addWidget(self.button)

        container = QWidget()
        container.setLayout(layout)
        self.setCentralWidget(container)

    def run_command(self):
        self.text_edit.clear()
        self.command_thread = CommandThread("ping 127.0.0.1 -n 10")
        self.command_thread.output_signal.connect(self.append_output)
        self.command_thread.start()

    def append_output(self, text):
        self.text_edit.append(text)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
```
</details>

Maybe you can try to add `shell=True` parameter to line 1860 or try [this solution](https://gist.github.com/nitely/3862493).

**Comment by ovo-Tim** [comment]
@oliveroxtoby I've finally done the rebase.

Git has almost drove me crazy, it seems I am badly in need of improving my git skill. :rofl:

**Comment by mmcker** [comment]
Hi,  there is also a stop_container in CfdOF/CfdPreferencePage.py that needs to be updated to your clean_container.

You ping code above didn't produce a window for me (under windows) but definitely the new clean_container does - I'm not sure why, but isn't a big deal - the window goes when the command finishes.

**Comment by ovo-Tim** [comment]
> there is also a stop_container in CfdOF/CfdPreferencePage.py that needs to be updated to your clean_container.

I've fixed this issue. 

By the way, don't you guys think those codes need to be formated by tools like ruff?

**Comment by oliveroxtoby** [comment]
> @oliveroxtoby I've finally done the rebase.
> 
> Git has almost drove me crazy, it seems I am badly in need of improving my git skill. 🤣

@ovo-Tim I'm not really seeing any change to your commits? There are still commits with descriptions like "Done" and "small change" which could presumably be squashed together into more meaningful chunks. Did you remember to push after the rebase?

> By the way, don't you guys think those codes need to be formated by tools like ruff?

I'm not familar with it, but I have no objection in principle.

**Comment by ovo-Tim** [comment]
>  Did you remember to push after the rebase?

@oliveroxtoby Sorry, I forgot force pushing, there should no longer be any problem now.

**Comment by hasecilu** [comment]
Hey, I tested this but got this error when checking dependencies, it's related on this PR or it's from the docker image?

```python
Checking for gmsh:
Uncaught exception:
   File "/home/uli/.local/share/FreeCAD/Mod/CfdOF/./CfdOF/CfdPreferencePage.py", line 278, in runDependencyChecker
    CfdTools.checkCfdDependencies(lambda msg:  (print(msg), self.consoleMessage(msg)))
  File "/home/uli/.local/share/FreeCAD/Mod/CfdOF/./CfdOF/CfdTools.py", line 1240, in checkCfdDependencies
    gmsh_exe = getGmshExecutable()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/uli/.local/share/FreeCAD/Mod/CfdOF/./CfdOF/CfdTools.py", line 1303, in getGmshExecutable
    gmsh_cmd = os.path.normpath(gmsh_cmd)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: _path_normpath: path should be string, bytes or os.PathLike, not NoneType
Traceback (most recent call last):
  File "/home/uli/.local/share/FreeCAD/Mod/CfdOF/./CfdOF/CfdPreferencePage.py", line 278, in runDependencyChecker
    CfdTools.checkCfdDependencies(lambda msg:  (print(msg), self.consoleMessage(msg)))
  File "/home/uli/.local/share/FreeCAD/Mod/CfdOF/./CfdOF/CfdTools.py", line 1240, in checkCfdDependencies
    gmsh_exe = getGmshExecutable()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/uli/.local/share/FreeCAD/Mod/CfdOF/./CfdOF/CfdTools.py", line 1303, in getGmshExecutable
    gmsh_cmd = os.path.normpath(gmsh_cmd)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _path_normpath: path should be string, bytes or os.PathLike, not NoneType
```

**Comment by hasecilu** [comment]
Yeah seems it's only it's supposed to check with your local binaries and not inside the container, not related here.

**Comment by mmcker** [comment]
@hasecilu 
Can you please provide the details of your system so I can test (see 5 below)?  Which docker image are you using?

5. Always include your FreeCAD version information. You can easily copy/paste all the needed information by using the "Copy to clipboard" button in FreeCAD, in menu Help -> About FreeCAD. You can then paste that information in your bug report.

**Comment by oliveroxtoby** [comment]
I have merged this after doing another rebase to fix some minor remaining issues in the commits.

**Comment by hasecilu** [comment]
> @hasecilu Can you please provide the details of your system so I can test (see 5 below)? Which docker image are you using?

docker.io/mmcker/cfdof-openfoam:latest.

Hisa, Cgmesh and openfoam binaries seem OK, trying to use gmesh error.

```
OS: Arch Linux (Hyprland/hyprland/wayland)
Architecture: x86_64
Version: 1.1.0dev.36460 +3048 (Git)
Build type: Release
Branch: test/prs
Hash: 753ff9c6f8adc2488a0e472ff07f061cf85e6062
Python 3.12.7, Qt 6.8.1, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: Spanish/Mexico (es_MX)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Installed mods: 
  * CfdOF 1.29.2
```

**Comment by mmcker** [comment]
Thanks  @hasecilu - I think i see that the problem is.
The docker container contains the gmesh and hisa internally - but it won't try to use the internal gmesh if the gmesh location is filled in the preference page.

Can you please delete the gmesh and hisa on preference page and see if that fixes the problem.  We will update the code.

**Comment by hasecilu** [comment]
They're empty

image

**Comment by ovo-Tim** [comment]
> The docker container contains the gmesh and hisa internally - but it won't try to use the internal gmesh if the gmesh location is filled in the preference page.

@mmcker  I don't think it will use gmesh inside of the container even though the gmesh location isn't filled. 

image

**Comment by mmcker** [comment]
Thanks Tim - the whole point of the docker image was that we could use the docker image and not worry about installing openfoam, gmesh and hisa.  It worked before.

I'll have to retest to see what is going on

**Pull request closed without merging**
