### PR TITLE
Rename commands to follow FreeCAD guidelines

### PR DESCRIPTION
**Pull request by hasecilu**
This change is to make when using "What's this?" feature on the CfdOF commands the correct Wiki documentation page is opened.

As I mentioned on previous PR I consider that is a good practice to match the command names on WB with the FreeCAD Wiki.

Here the main problem is that in the Addon manager also appears another WB called **Cfd** as in <https://wiki.freecad.org/Cfd_Workbench>, I think is the first version of the WB.

Of course in the Wiki is also this WB <https://wiki.freecad.org/CfdOF_Workbench> and as you can see in the commands pages use "CfdOF\_" prefix.

Even with this changes you can notice still are few discrepancies but Wiki articles can also be renamed, we can ask that here: <https://forum.freecad.org/viewtopic.php?t=85208>

What do you think with this changes?

### CODE REVIEW

**Comment by oliveroxtoby** [comment]
Perfect. Thank you very much @hasecilu!

**Comment by Syres916** [comment]
Much appreciated, also inspirational, after 1.0 prep work has calmed down I'm going to look at getting the same for Silk Wb, thanks again @hasecilu

**Comment by hasecilu** [comment]
> Much appreciated, also inspirational, after 1.0 prep work has calmed down I'm going to look at getting the same for Silk Wb, thanks again @hasecilu

That would be awesome, don't hesitate to contact me to get Spanish translation, I bet @kaktusus would be also interested to help on testing.

**Comment by kaktusus** [comment]
Working in a team is faster and more efficient and more enjoyable.

:smiley:

**Pull request merged**
