### PR TITLE
Add config files to help on formatting

### PR DESCRIPTION
**Pull request by hasecilu**
As mentioned on: https://github.com/jaheyns/CfdOF/pull/191#issuecomment-2516590192

- `.ruff.toml` is a config file used by [ruff](https://docs.astral.sh/ruff/) formatter; it's set to use 100 char lines, indent with 4 spaces, use double quote for strings, etc. in order to be compatible with **black**. It happens to be the one I use for every FreeCAD-related stuff, I use it on [STEMFIE](https://github.com/bilbaomakers/StemfieWB) and [FreeGrid](https://github.com/instancezero/in3dca-freegrid) WBs, macros and also when I'm editing files from FreeCAD source code **I don't find conflicts**.
- `.pre-commit-config.yaml` Main FreeCAD code uses a `pre-commit` hook to format Python to be 100 char line width max. [^1] I also like having 100 chars because 80 feels to short. There are also some small generic hooks. Finally, to prevent typos on the code I use a codespell hook, I included a file where we can put strings that trigger a typo detection wrong (`.codespellrc`). Btw, no typos here :100: .

### [pre-commit](https://pre-commit.com/)

Snippets of code executed before commiting. Local use, CI-bot not included but could use the same config file.

1. Install it `sudo pacman -S pre-commit`
2. Once inside the repo execute `pre-commit install`, that will install the hook based on the content of the config file.
3. When committing the hooks will be run against the staged files, if there are problems the commit is not done and you have to fix it.

If you want to se the changes that would be done after executing on all files check this branch (`pre-commit run --all-files`): https://github.com/jaheyns/CfdOF/compare/master...hasecilu:CfdOF:chore/formattin_full

Not sure if it's better the formatting changes all in a single commit, or just do it little by little, just change the files you're working on.

### extra

- Of course if there are other config files for other Python formatters I think would be nice to also include them.
- I'm working on part 2 of translation support so would be good to know if these changes proceed to avoid merge conflicts when I finish.

[^1]: https://github.com/FreeCAD/FreeCAD/blob/a97677ed2f0ee4875321f3043782cf77e3756cc6/.pre-commit-config.yaml#L64

### CODE REVIEW

**Comment by hasecilu** [comment]
> Hi, perhaps you might consider using [ruff](https://github.com/astral-sh/ruff-pre-commit) for pre-commit hooks instead of black. Additionally, it would be beneficial to incorporate the [ruff action](https://github.com/astral-sh/ruff-action) for automatic format checks.

Have you tested with code of FreeCAD projects? I suppose it's equivalent to black, honestly I just use black because that's the thing used by FreeCAD, I use ruff on Neovim though.

**Comment by ovo-Tim** [comment]
> I suppose it's equivalent to black, honestly I just use black because that's the thing used by FreeCAD

Yeah, their behaviors should be equivalent and ruff is faster, so I consider ruff as a better choice. Additionally, we don't have to be exactly same as FreeCAD.

**Comment by oliveroxtoby** [comment]
Thank you @hasecilu for this. I'm afriad I don't have experience with these tools to allow me to referee the ruff-vs-black question. I would just request that we use the one with the fewest dependencies, if any. I think the lower the barrier to developers using it, the better. But all else being equal, I guess if ruff is equivalent and faster, we might as well use it. 

One thing: Could I just request that the add the instructions above on how to enable the pre-commit hooks to the CONTRIBUTING.md file, please?

**Comment by hasecilu** [comment]
Hi, I have updated the file wit pre-commit instructions and other comments, file [here](https://github.com/hasecilu/CfdOF/blob/chore/formatting/CONTRIBUTING.md); it got all reformatted because of the trailing spaces and maybe Windows end of line?

I haven't used any of these tools on Windows so I'm not sure how good is GitBash or Python there, I suppose that if people use WSL would be the same.

I tested with ruff hooks and worked pretty good, even takes care of some linting stuff as:
2024-12-12-081101_hyprshot


I saw that the CONTRIBUTING file stated :
> 2. Limit all lines to a maximum of 120 characters.

and despite 100 lines is compliant if you want I can change the ruff config file to use 120 char line width, I set 100 originally just because that's the value used on FreeCAD.

Let me know if changes are needed.

**Comment by oliveroxtoby** [comment]
Thank you! It looks good to me. The 120 character limit was just a personal preference, but I think it makes sense to rather harmonise with FreeCAD, so let's go with 100.

**Comment by hasecilu** [comment]
Cool, now I think just be needed to run the hooks to format all the files in case you want to. In that case would be better to first merge the part 2 of translations PR.

**Pull request merged**
