### PR TITLE
Docker functionality added

### PR DESCRIPTION
**Pull request by mmcker**
Revised as one commit.  Passing usedocker to functions replaced with getFoamRuntime()

### CODE REVIEW

**Comment by oliveroxtoby** [comment]
Thanks @mmcker, this looks good to me. One last request - please could you add the installation instructions (similar to what you posed on the forum) to the README?

**Comment by luzpaz** [comment]
FreeCAD core could really benefit from some good docker integration (hint hint nudge nudge) :smirk:

**Comment by mmcker** [comment]
I have updated Readme.md and the windows code as the recent change broke the windows install.

I have made a meal of the git commits so I'll have to revert them all and do one commit.

@luzpaz no problems (when I get this one right!). Are there any links to forum posts on what applications integration is required for?  I guess it would be a generalized version of the cfdof implementation - perhaps for some of the other FEM solvers?

**Comment by oliveroxtoby** [comment]
Continued in #67

**Pull request closed without merging**
